first_app/urls.py
from django.urls import path

from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.index),
    path('index/', views.index),
    path('help/', views.help),
    path('image/',views.image),
    path('webpages/',views.webpages),
    path('users/',views.users),
    path('form_name/',views.form_name),
    path('new_user/',views.new_user_form),
    path('page_one/',views.page_one),
    path('other/',views.other),
    path('other_five/',views.other_five),
    path('new_page/',views.new_page),
    path('other_three/',views.other_three, name='other_three'),
    path('other_four/',views.other_four, name='other_four'),
    path('base/',views.base),
    path('base_other/',views.base_other, name='base_other'),
    path('home/',views.home, name='home'),
    path('template_home/',views.template_home, name='template_home'),
    path('template_users/',views.template_users, name='template_users'),
    path('template_form/',views.template_form, name='template_form'),
]

second_project/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from first_app import views
urlpatterns = [
    #path('', views.index),
    path('first_app/', include('first_app.urls')),
    path('second_app/', include('second_app.urls')),
    path('admin/', admin.site.urls),
]

first_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    date = models.DateField()
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)
    
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=256, unique=True)


    def __str__(self):
        return self.first_name+' '+self.last_name



#class first_name(models.Model)

first_app/forms.py
from django import forms
from django.core import validators

from .models import User


def validate_email(value):
    if 'gmail.com' not in value:
        print("Raise Error")
        raise forms.ValidationError("Gmail accepted only")
    
def validate_name_length(value):
    if len(value) < 5:
        print("Raise Error")
        raise forms.ValidationError("Name must be 5 characters or longer")
    
def validate_name_letter(value):
    if value[0].lower() != 'z':
        print("Raise Error - First Letter Not Z")
        raise forms.ValidationError("Name must begin with the letter Z")


class FormName(forms.Form):
    name = forms.CharField(validators=[validators.MinLengthValidator(5),validate_name_letter])
    email = forms.EmailField(validators=[validators.MinLengthValidator(15),validate_email])
    v_email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    
    def clean(self):

        if self.is_valid():
           data = super().clean()
           email = data['email']
           v_email = data['v_email']
           print("Clean Method 2")

           if v_email != email:
              print("Raise Error - Emails Different")
              raise forms.ValidationError("The emails are not the same")
           
class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

first_app/views.py
from django.shortcuts import render
from .models import Topic,Webpage,AccessRecord,User
from . import forms


# Create your views here.

def index(request):

    my_dict = {"insert_me" : "Hello I am coming from views.py"}

    return render(request, "first_app/index.html", my_dict)
    
def help(request):

    my_dict = {"second_text": "I'm here to help"}

    return render(request, "first_app/help.html", my_dict)

def image(request):

    return render(request, "first_app/image.html")

def webpages(request):
    
    # Gets Data from the DB.
    webpages_list = AccessRecord.objects.order_by('date')

    # Puts the data in a dictionary
    webpages_dict = { "webpages": webpages_list }

    # Pass the dictionary to the template
    return render(request,'first_app/webpages.html', webpages_dict) 

def users(request):

    users_list = User.objects.order_by('last_name')

    users_dict = { "users" : users_list }

    return render(request, 'first_app/users.html', users_dict)

def form_name(request):

    form = forms.FormName()
    
    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("Success")
            print("NAME: " + form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])
            form = forms.FormName()
       

    return render(request, 'first_app/form_page.html', { 'form':form })

def new_user_form(request):
    form = forms.NewUserForm();
    
    if request.method == "POST":
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            print("User saved!")
            return users(request)
        else: 
            print('Invalid form')

    return render(request,'first_app/new_user.html', {'form':form} )

def users(request):

    users_list = User.objects.order_by('last_name')

    users_dict = { "users": users_list }

    return render(request, 'first_app/users.html', users_dict)

def page_one(request):
    return render(request, "first_app/page_one.html")

def other(request):
    return render(request, 'first_app/page_two.html')

def other_three(request):
    return render(request, 'first_app/page_three.html')

def other_four(request):
    return render(request, 'first_app/page_four.html')

def new_page(request):
    return render(request, 'first_app/page_new.html')

def other_five(request):
    return render(request, 'first_app/page_five.html')


def base(request):
    return render(request, 'first_app/base.html')

def base_other(request):
    return render(request, 'first_app/other.html')

def home(request):
    return render(request, 'first_app/home.html')

def template_home(request):
    return render(request, 'first_app/template_home.html')

def template_users(request):
    return render(request, 'first_app/template_users.html')


def template_form(request):
    form = forms.NewUserForm();
    
    if request.method == "POST":
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            print("User saved!")
            return users(request)
        else: 
            print('Invalid form')

    return render(request,'first_app/template_form.html', {'form':form} )

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Template Inheritance</title>
</head>
<body>
    <div class="container mt-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'first_app:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:base_other' %}">Other</a>
            </li>
          </ul>

        </div>
      </nav>

      {% block body_block %}
      {# Anything outside of this will be inherited if you use extend. #}
      {% endblock %}
    </div>
</body>
</html>

templates/first_app/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        This is a help page
    </h1>

    {{second_text}}
</body>
</html>

templates/first_app/home.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
    <h1>Hello and welcome to the site!</h1>
    {% endblock %}

templates/first_app/image.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/my_styles.css' %}">
</head>
<body>
    <h1>Hello this is image.html</h1>
    <img src="{% static 'images/django.jpg' %}" alt="Uh Oh, didn't show">
</body>
</html>

templates/first_app/new_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New User</title>
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Please sign up here!</h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>

</body>
</html>

templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
    <h1>This is an example of template inheritance!</h1>
    <h2>This is other.html page</h2>
    {% endblock %}

templates/first_app/page_five.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Page five</title>
</head>
<body>
    <h1>This is page five!</h1>
</body>
</html>

templates/first_app/page_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative URLs</title>
</head>
<body>
    <h1>Welcome to Page One</h1>
    <p>
        This page serves as an example of how to use Relative
        URLs with templates
    </p>
    

    <div>
        <a href="/first_app/other">Link to page_two.html</a>
    </div>
    <div>
        <a href="{% url 'first_app:other_three' %}">Link to page_three.html</a>
    </div>


</body>
</html>

templates/first_app/page_three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Three</title>
</head>
<body>
    <h1>Page three</h1>
</body>
</html>

templates/first_app/page_two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page two</title>
</head>
<body>
    <h1>This is page two</h1>
    

</body>
</html>

templates/first_app/template_form.html
<!DOCTYPE html>
{% extends "first_app/Template_page.html" %}
    {% block body_block %}
    <h1 class="mb-4">Please sign up here!</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
       <input type="submit" class="btn btn-primary" value="Submit">
    </form>
    {% endblock %}

templates/first_app/template_home.html
<!DOCTYPE html>
{% extends "first_app/Template_page.html" %}
    {% block body_block %}
    <div class="jumbotron mt-4">
        <h1 class="display-4">Home</h1>
        <p class="lead">Welcome to the site!</p>
        </div>
    {% endblock %}

templates/first_app/template_users.html
<!DOCTYPE html>
{% extends "first_app/Template_page.html" %}
    {% block body_block %}
    <div>
        {% if users %}

            <table class="table table-primary table-striped table-hover">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                </thead>

                {% for user in users %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
            </table>

        {% else %}
        <p>No users</p>
        {% endif %}
    </div>
    {% endblock %}

templates/first_app/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Users</title>
    <link rel="stylesheet" href="{% static 'css/my_styles.css' %}">
</head>
</head>
<body>
    <div class="container w-50" >
    <h1>Hi, Welcome to my Django App</h1>
    <h2>Here are your users</h2>
    <div>
        {% if users %}

            <table class="table table-primary table-striped table-hover">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                </thead>

                {% for user in users %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
            </table>

        {% else %}
        <p>No users</p>
        {% endif %}
    </div>
    </div>
</body>
</html>