first_app/urls.py
from django.urls import path

from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.index),
    path('index/', views.index),
    path('help/', views.help),
    path('image/',views.image),
    path('webpages/',views.webpages),
    path('users/',views.users),
    path('form_name/',views.form_name),
    path('new_user/',views.new_user_form),
    path('page_one/',views.page_one),
    path('other/',views.other),
    path('other_five/',views.other_five),
    path('new_page/',views.new_page),
    path('other_three/',views.other_three, name='other_three'),
    path('other_four/',views.other_four, name='other_four'),
    path('base/',views.base),
    path('base_other/',views.base_other, name='base_other'),
    path('home/',views.home, name='home'),
    path('template_home/',views.template_home, name='template_home'),
    path('template_users/',views.template_users, name='template_users'),
    path('template_form/',views.template_form, name='template_form'),
]

second_app/urls.py
from django.urls import path

from second_app import views

app_name = "second_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_register/', views.user_register, name='user_register'),
    path('user_list/', views.user_list, name='user_list'),
]

second_project/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from first_app import views
urlpatterns = [
    #path('', views.index),
    path('first_app/', include('first_app.urls')),
    path('second_app/', include('second_app.urls')),
    path('admin/', admin.site.urls),
]

second_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    # This is a relationship, not an inheritance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add additional attributes
    portfolio_site = models.URLField(blank=True)

    #profile_pic = models.ImageField(upload_to='second_app/profile_pics',blank=True)
    profile_pic = models.ImageField(upload_to='images/',blank=True)

    def __str__(self):
        return self.user.username + " - " + self.user.first_name + " " + self.user.last_name

second_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

second_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from .models import User, UserProfileInfo


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'second_app/index.html')

@login_required
def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('second_app:index'))

def user_login(request):

    if request.method == 'POST':

        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        print(username)
        print(password)

        # Django's built-in authentication function
        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request,user)

                #Send the user back to the homepage.
                return HttpResponseRedirect(reverse('second_app:index'))
            else:
                # If the account is not active
                return HttpResponse("Your account is not active")
        else:
            print("Someone tried to login and failed")
            print(f"They used username: {username} and password: {password}")

            return HttpResponse("Invalid login details supplied")
    else:
       return render(request, 'second_app/login.html', {})
       
def user_register(request):

    registered: bool = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            # Save the User Form to a database
            user = user_form.save()

            #Hash the password
            user.set_password(user.password)

            # Update with Hashed Password
            user.save()

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES: 
                print('picture found')
                profile.profile_pic = request.FILES['profile_pic']
            else:
                print('picture not found')

            # Save the profile
            profile.save()

            # Registration successful
            registered =  True
        else:
            # One of the forms or both are invalid.
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'second_app/register.html', { 'user_form': user_form, 'profile_form':profile_form, 'registered': registered })

def user_list(request):
    
    users_list = User.objects.order_by('username')
    profiles_dict = {}
    for user in users_list:
        try:
            profile = UserProfileInfo.objects.get(user=user)
            #profile.profile_pic = profile.profile_pic.
            print(profile.profile_pic)
            profiles_dict[user.username] = profile
        except UserProfileInfo.DoesNotExist:
            pass
# this is a comment
    print(profiles_dict)
    users_dict = { "users" : users_list, "profiles" : profiles_dict }

    return render(request, 'second_app/user_list.html', users_dict)

templates/second_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'second_app:user_register' %}">Register</a>
            </li>
      {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'second_app:user_logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'second_app:user_list' %}">User List</a>
            </li>
      {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'second_app:user_login' %}">Login</a>
            </li>
      {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container mt-4">
        {% block body_block %}
        {% endblock %}
      </div>
</body>
</html>

templates/second_app/index.html
{% extends  "second_app/base.html" %}
{% block body_block %}

<div class="jumbotron mt-5">
    <h1>Welcome to Django</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site</h2>
    {% endif %}
</div>

{% endblock %}

templates/second_app/login.html
{% extends  "second_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form method="post" action="{% url 'second_app:user_login' %}">

        {% csrf_token %}
        {# A more "HTML" way of creating a login form #}

        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username">

        <label for="password"></label>
        <input type="password" name="password">

        <input type="submit" value="Login">

    </form>
</div>

{% endblock %}

templates/second_app/register.html
{% extends  "second_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" value="Register"></input>

        </form>

    {% endif%}
</div>

{% endblock %}

templates/second_app/user_list.html
{% extends  "second_app/base.html" %}
{% block body_block %}
{% load static %}
<div class="w-75">
    {% if users %}

        <table class="table table-primary table-striped table-hover">
            <thead>
                <th>Username</th>
                <th>Email</th>
                <th>Website</th>
                <th>Profile Picture</th>
            </thead>

            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        {% for key, value in profiles.items %}
                            {% if key == user.username %}
                                {{ value.portfolio_site }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td class="text-center">
                        {% for key, value in profiles.items %}
                            {% if key == user.username %}
                            <img src="{% static value.profile_pic %}" class="img-fluid dtext-center" style="max-width: 25%; height: auto" alt="Uh Oh, didn't show">
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
    <p>No users</p>
    {% endif %}
</div>


{% endblock %}